[project]
name = "ORCESTRA-api"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
