################################################################################
# Project Configuration
################################################################################
[project]
name = "snakemake-orcestrator-api"
version = "0.7.0"
description = "Add a short description here"
authors = [
    {name = "Jermiah Joseph", email = "jermiah.joseph@uhn.ca"},
    {name = "Matthew Boccolon", email = "matthew.boccolon@uhn.ca"}
    ]
requires-python = ">= 3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "orcestrator",
]

################################################################################
# PIXI Configuration
################################################################################

[tool.pixi.project]
name = "snakemake-orcestrator-api"
version = "0.7.0"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.system-requirements]
linux = "5.4.203"               # This is for my linux machine

[tool.pixi.pypi-dependencies]

[tool.pixi.dependencies]
python = "3.12.*"
pydantic = ">=2.6.4,<2.7"
motor = ">=3.4.0,<3.5"
snakemake = "==7.32.4"

[tool.pixi.tasks]

[tool.pixi.environments]
default = { features = ["dev", "build"], solve-group = "default" }
prod = { features = ["prod"], solve-group = "prod" }

[tool.pixi.feature.dev.dependencies]
python-semantic-release = ">=9.4.0,<9.5"
pre-commit = ">=3.7.0,<3.8"

[tool.pixi.feature.dev.pypi-dependencies]
ORCESTRA-api = { path = ".", editable = true }

[tool.pixi.feature.dev.tasks]
test = "python -c 'print(\"Hello, World!\")'"
hello = { cmd = "python -m src.core.main", depends_on = ["test"] }

[tool.pixi.feature.build.dependencies]
build = "*"
hatchling = ">=1.24.2,<1.25"

[tool.pixi.feature.build.tasks]
wheel = "python -m build --no-isolation --wheel ."

[tool.pixi.feature.prod]


################################################################################
# Semantic Release Configuration
################################################################################

[tool.semantic_release]
commit_message = "{version} [ci skip]\n\nAuto-generated by semantic-release."
commit_parser = "angular"
logging_use_named_masks = true
tag_format = "v{version}"
version_toml = [
    "pyproject.toml:project.version",
    "pyproject.toml:tool.pixi.project.version",
]

[tool.semantic_release.branches.main]
match = "(main|master)"

[tool.semantic_release.changelog]
changelog_file = "docs/topics/CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "style",
    "refactor",
    "revert",
    "test",
    "merge",
]

minor_tags = ["feat"]

patch_tags = [
    "fix",
    "perf",
    "build",
    "ci",
    "chore",
    "docs",
    "refactor",
    "style",
    "test",
]
