[semantic_release]
version_variables = ["src/orcestrator/__init__.py:__version__"]
version_toml = [
  "pyproject.toml:project.version",
  "pyproject.toml:tool.pixi.version",
]
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
tag_format = "v{version}"

[semantic_release.branches.main]
match = "(main|master)"

[semantic_release.branches.develop]
match = "(dev|develop)"
prerelease_token = "rc"
prerelease = true

[semantic_release.changelog]
template_dir = "templates"
changelog_file = "docs/CHANGELOG.md"
exclude_commit_patterns = []

[semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[semantic_release.commit_parser_options]
allowed_tags = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "style",
  "refactor",
  "test",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0

[semantic_release.remote]
token = { env = "GITHUB_TOKEN" }
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false

[semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true