name: Merge main into staging and development

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge and push to staging
        run: |
          git checkout staging
          git merge --no-ff main -m "Merge main into staging [ci skip]"
          git push origin staging

      - name: Merge and push to development
        run: |
          git checkout development
          git merge --no-ff main -m "Merge main into development [ci skip]"
          git push origin development
